//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.1
//     from Assets/Scripts/Input/VRController_InputActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @VRController_InputActions : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @VRController_InputActions()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""VRController_InputActions"",
    ""maps"": [
        {
            ""name"": ""VRControllers"",
            ""id"": ""913ad3e0-7b4f-43ab-a5e6-39cfb2d1c940"",
            ""actions"": [
                {
                    ""name"": ""Trigger_Right"",
                    ""type"": ""Value"",
                    ""id"": ""145b6e74-9e78-4b95-96a8-878fe3919987"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Trigger_Left"",
                    ""type"": ""Value"",
                    ""id"": ""e9878729-eb18-471b-80c3-e587090de60a"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Velocities_Right"",
                    ""type"": ""Value"",
                    ""id"": ""7e4e8a61-032b-4870-b3a6-cea2ba931b34"",
                    ""expectedControlType"": ""Vector3"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Velocities_Left"",
                    ""type"": ""Value"",
                    ""id"": ""9c767e85-abe5-4210-b0ca-33899937d939"",
                    ""expectedControlType"": ""Vector3"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""AngularVelocities_Right"",
                    ""type"": ""Value"",
                    ""id"": ""817a004f-a175-4a47-8a96-02e86d574ec9"",
                    ""expectedControlType"": ""Vector3"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""AngularVelocities_Left"",
                    ""type"": ""Value"",
                    ""id"": ""fc579f97-7658-415d-bf63-36a0deefad0e"",
                    ""expectedControlType"": ""Vector3"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""ButtonPrimary_Right"",
                    ""type"": ""PassThrough"",
                    ""id"": ""7282c8c6-9f0c-476d-a646-d422f622a2d8"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Joystick_Left"",
                    ""type"": ""Value"",
                    ""id"": ""0dacbb91-5e8b-41f7-9e51-31c796f22c6f"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""75c9d7d8-fcee-4e60-905f-5c1861d395d6"",
                    ""path"": ""<OculusTouchController>{RightHand}/trigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Trigger_Right"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3dc8c8ee-8d16-4f2d-ab89-7b5623abf9ac"",
                    ""path"": ""<ViveController>{RightHand}/trigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Trigger_Right"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6918b9c3-be84-499b-89be-cdc0712c1212"",
                    ""path"": ""<OculusTouchController>{LeftHand}/trigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Trigger_Left"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""799ecbf2-805a-4f5c-bea7-0062996f07ab"",
                    ""path"": ""<ViveController>{LeftHand}/trigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Trigger_Left"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f71d419e-9d2c-40a7-bcb6-72a6effb523c"",
                    ""path"": ""<OculusTouchController>{RightHand}/pointer/velocity"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Velocities_Right"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f5271f43-d22c-4706-bb91-e0680fcc8409"",
                    ""path"": ""<ViveController>{RightHand}/pointer/velocity"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Velocities_Right"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3b1a469e-ba9d-4d2e-8ecb-85db4510a990"",
                    ""path"": ""<OculusTouchController>{LeftHand}/pointer/velocity"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Velocities_Left"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8433baf7-2abf-4265-8e29-ebd4408cd48a"",
                    ""path"": ""<ViveController>{LeftHand}/pointer/velocity"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Velocities_Left"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f4bafe07-800a-4213-b0ab-8b9276f9db96"",
                    ""path"": ""<OculusTouchController>{RightHand}/pointer/angularVelocity"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""AngularVelocities_Right"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7f6cbd21-84b7-473a-ac7e-9be5acd00c73"",
                    ""path"": ""<ViveController>{RightHand}/pointer/angularVelocity"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""AngularVelocities_Right"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""dbca78ad-3309-4c1f-9f76-89aa5382c33e"",
                    ""path"": ""<OculusTouchController>{LeftHand}/pointer/angularVelocity"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""AngularVelocities_Left"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""382714d0-c276-4683-93aa-2ec053b1f34b"",
                    ""path"": ""<ViveController>{LeftHand}/pointer/angularVelocity"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""AngularVelocities_Left"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""451b0567-e689-41c4-bdd6-0cd8194b118c"",
                    ""path"": ""<OculusTouchController>{RightHand}/primaryButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ButtonPrimary_Right"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""01b2c9e5-5bfc-4292-8890-6bc1441c5665"",
                    ""path"": ""<ViveController>{RightHand}/trackpadClicked"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ButtonPrimary_Right"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""87755075-e6dd-45a8-a59f-ca80d62cae0b"",
                    ""path"": ""<OculusTouchController>{LeftHand}/thumbstick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Joystick_Left"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""VRControllerHTC"",
            ""id"": ""f61993b3-1040-40b9-af1d-9fe6c0a13abf"",
            ""actions"": [
                {
                    ""name"": ""Joystick_Left"",
                    ""type"": ""Value"",
                    ""id"": ""b7838fcf-c599-4cdb-93b1-bcf5f032b933"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""TrackpadTouched_Left"",
                    ""type"": ""PassThrough"",
                    ""id"": ""d41e66e1-1751-4618-bfec-230fe7ebd4bf"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""857cb6fe-31be-44a1-8d87-182e3d2c9803"",
                    ""path"": ""<ViveController>{LeftHand}/trackpad"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Joystick_Left"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8a6b518d-b033-454c-99c6-cb784acf9533"",
                    ""path"": ""<ViveController>{LeftHand}/trackpadTouched"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TrackpadTouched_Left"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // VRControllers
        m_VRControllers = asset.FindActionMap("VRControllers", throwIfNotFound: true);
        m_VRControllers_Trigger_Right = m_VRControllers.FindAction("Trigger_Right", throwIfNotFound: true);
        m_VRControllers_Trigger_Left = m_VRControllers.FindAction("Trigger_Left", throwIfNotFound: true);
        m_VRControllers_Velocities_Right = m_VRControllers.FindAction("Velocities_Right", throwIfNotFound: true);
        m_VRControllers_Velocities_Left = m_VRControllers.FindAction("Velocities_Left", throwIfNotFound: true);
        m_VRControllers_AngularVelocities_Right = m_VRControllers.FindAction("AngularVelocities_Right", throwIfNotFound: true);
        m_VRControllers_AngularVelocities_Left = m_VRControllers.FindAction("AngularVelocities_Left", throwIfNotFound: true);
        m_VRControllers_ButtonPrimary_Right = m_VRControllers.FindAction("ButtonPrimary_Right", throwIfNotFound: true);
        m_VRControllers_Joystick_Left = m_VRControllers.FindAction("Joystick_Left", throwIfNotFound: true);
        // VRControllerHTC
        m_VRControllerHTC = asset.FindActionMap("VRControllerHTC", throwIfNotFound: true);
        m_VRControllerHTC_Joystick_Left = m_VRControllerHTC.FindAction("Joystick_Left", throwIfNotFound: true);
        m_VRControllerHTC_TrackpadTouched_Left = m_VRControllerHTC.FindAction("TrackpadTouched_Left", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // VRControllers
    private readonly InputActionMap m_VRControllers;
    private IVRControllersActions m_VRControllersActionsCallbackInterface;
    private readonly InputAction m_VRControllers_Trigger_Right;
    private readonly InputAction m_VRControllers_Trigger_Left;
    private readonly InputAction m_VRControllers_Velocities_Right;
    private readonly InputAction m_VRControllers_Velocities_Left;
    private readonly InputAction m_VRControllers_AngularVelocities_Right;
    private readonly InputAction m_VRControllers_AngularVelocities_Left;
    private readonly InputAction m_VRControllers_ButtonPrimary_Right;
    private readonly InputAction m_VRControllers_Joystick_Left;
    public struct VRControllersActions
    {
        private @VRController_InputActions m_Wrapper;
        public VRControllersActions(@VRController_InputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @Trigger_Right => m_Wrapper.m_VRControllers_Trigger_Right;
        public InputAction @Trigger_Left => m_Wrapper.m_VRControllers_Trigger_Left;
        public InputAction @Velocities_Right => m_Wrapper.m_VRControllers_Velocities_Right;
        public InputAction @Velocities_Left => m_Wrapper.m_VRControllers_Velocities_Left;
        public InputAction @AngularVelocities_Right => m_Wrapper.m_VRControllers_AngularVelocities_Right;
        public InputAction @AngularVelocities_Left => m_Wrapper.m_VRControllers_AngularVelocities_Left;
        public InputAction @ButtonPrimary_Right => m_Wrapper.m_VRControllers_ButtonPrimary_Right;
        public InputAction @Joystick_Left => m_Wrapper.m_VRControllers_Joystick_Left;
        public InputActionMap Get() { return m_Wrapper.m_VRControllers; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(VRControllersActions set) { return set.Get(); }
        public void SetCallbacks(IVRControllersActions instance)
        {
            if (m_Wrapper.m_VRControllersActionsCallbackInterface != null)
            {
                @Trigger_Right.started -= m_Wrapper.m_VRControllersActionsCallbackInterface.OnTrigger_Right;
                @Trigger_Right.performed -= m_Wrapper.m_VRControllersActionsCallbackInterface.OnTrigger_Right;
                @Trigger_Right.canceled -= m_Wrapper.m_VRControllersActionsCallbackInterface.OnTrigger_Right;
                @Trigger_Left.started -= m_Wrapper.m_VRControllersActionsCallbackInterface.OnTrigger_Left;
                @Trigger_Left.performed -= m_Wrapper.m_VRControllersActionsCallbackInterface.OnTrigger_Left;
                @Trigger_Left.canceled -= m_Wrapper.m_VRControllersActionsCallbackInterface.OnTrigger_Left;
                @Velocities_Right.started -= m_Wrapper.m_VRControllersActionsCallbackInterface.OnVelocities_Right;
                @Velocities_Right.performed -= m_Wrapper.m_VRControllersActionsCallbackInterface.OnVelocities_Right;
                @Velocities_Right.canceled -= m_Wrapper.m_VRControllersActionsCallbackInterface.OnVelocities_Right;
                @Velocities_Left.started -= m_Wrapper.m_VRControllersActionsCallbackInterface.OnVelocities_Left;
                @Velocities_Left.performed -= m_Wrapper.m_VRControllersActionsCallbackInterface.OnVelocities_Left;
                @Velocities_Left.canceled -= m_Wrapper.m_VRControllersActionsCallbackInterface.OnVelocities_Left;
                @AngularVelocities_Right.started -= m_Wrapper.m_VRControllersActionsCallbackInterface.OnAngularVelocities_Right;
                @AngularVelocities_Right.performed -= m_Wrapper.m_VRControllersActionsCallbackInterface.OnAngularVelocities_Right;
                @AngularVelocities_Right.canceled -= m_Wrapper.m_VRControllersActionsCallbackInterface.OnAngularVelocities_Right;
                @AngularVelocities_Left.started -= m_Wrapper.m_VRControllersActionsCallbackInterface.OnAngularVelocities_Left;
                @AngularVelocities_Left.performed -= m_Wrapper.m_VRControllersActionsCallbackInterface.OnAngularVelocities_Left;
                @AngularVelocities_Left.canceled -= m_Wrapper.m_VRControllersActionsCallbackInterface.OnAngularVelocities_Left;
                @ButtonPrimary_Right.started -= m_Wrapper.m_VRControllersActionsCallbackInterface.OnButtonPrimary_Right;
                @ButtonPrimary_Right.performed -= m_Wrapper.m_VRControllersActionsCallbackInterface.OnButtonPrimary_Right;
                @ButtonPrimary_Right.canceled -= m_Wrapper.m_VRControllersActionsCallbackInterface.OnButtonPrimary_Right;
                @Joystick_Left.started -= m_Wrapper.m_VRControllersActionsCallbackInterface.OnJoystick_Left;
                @Joystick_Left.performed -= m_Wrapper.m_VRControllersActionsCallbackInterface.OnJoystick_Left;
                @Joystick_Left.canceled -= m_Wrapper.m_VRControllersActionsCallbackInterface.OnJoystick_Left;
            }
            m_Wrapper.m_VRControllersActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Trigger_Right.started += instance.OnTrigger_Right;
                @Trigger_Right.performed += instance.OnTrigger_Right;
                @Trigger_Right.canceled += instance.OnTrigger_Right;
                @Trigger_Left.started += instance.OnTrigger_Left;
                @Trigger_Left.performed += instance.OnTrigger_Left;
                @Trigger_Left.canceled += instance.OnTrigger_Left;
                @Velocities_Right.started += instance.OnVelocities_Right;
                @Velocities_Right.performed += instance.OnVelocities_Right;
                @Velocities_Right.canceled += instance.OnVelocities_Right;
                @Velocities_Left.started += instance.OnVelocities_Left;
                @Velocities_Left.performed += instance.OnVelocities_Left;
                @Velocities_Left.canceled += instance.OnVelocities_Left;
                @AngularVelocities_Right.started += instance.OnAngularVelocities_Right;
                @AngularVelocities_Right.performed += instance.OnAngularVelocities_Right;
                @AngularVelocities_Right.canceled += instance.OnAngularVelocities_Right;
                @AngularVelocities_Left.started += instance.OnAngularVelocities_Left;
                @AngularVelocities_Left.performed += instance.OnAngularVelocities_Left;
                @AngularVelocities_Left.canceled += instance.OnAngularVelocities_Left;
                @ButtonPrimary_Right.started += instance.OnButtonPrimary_Right;
                @ButtonPrimary_Right.performed += instance.OnButtonPrimary_Right;
                @ButtonPrimary_Right.canceled += instance.OnButtonPrimary_Right;
                @Joystick_Left.started += instance.OnJoystick_Left;
                @Joystick_Left.performed += instance.OnJoystick_Left;
                @Joystick_Left.canceled += instance.OnJoystick_Left;
            }
        }
    }
    public VRControllersActions @VRControllers => new VRControllersActions(this);

    // VRControllerHTC
    private readonly InputActionMap m_VRControllerHTC;
    private IVRControllerHTCActions m_VRControllerHTCActionsCallbackInterface;
    private readonly InputAction m_VRControllerHTC_Joystick_Left;
    private readonly InputAction m_VRControllerHTC_TrackpadTouched_Left;
    public struct VRControllerHTCActions
    {
        private @VRController_InputActions m_Wrapper;
        public VRControllerHTCActions(@VRController_InputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @Joystick_Left => m_Wrapper.m_VRControllerHTC_Joystick_Left;
        public InputAction @TrackpadTouched_Left => m_Wrapper.m_VRControllerHTC_TrackpadTouched_Left;
        public InputActionMap Get() { return m_Wrapper.m_VRControllerHTC; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(VRControllerHTCActions set) { return set.Get(); }
        public void SetCallbacks(IVRControllerHTCActions instance)
        {
            if (m_Wrapper.m_VRControllerHTCActionsCallbackInterface != null)
            {
                @Joystick_Left.started -= m_Wrapper.m_VRControllerHTCActionsCallbackInterface.OnJoystick_Left;
                @Joystick_Left.performed -= m_Wrapper.m_VRControllerHTCActionsCallbackInterface.OnJoystick_Left;
                @Joystick_Left.canceled -= m_Wrapper.m_VRControllerHTCActionsCallbackInterface.OnJoystick_Left;
                @TrackpadTouched_Left.started -= m_Wrapper.m_VRControllerHTCActionsCallbackInterface.OnTrackpadTouched_Left;
                @TrackpadTouched_Left.performed -= m_Wrapper.m_VRControllerHTCActionsCallbackInterface.OnTrackpadTouched_Left;
                @TrackpadTouched_Left.canceled -= m_Wrapper.m_VRControllerHTCActionsCallbackInterface.OnTrackpadTouched_Left;
            }
            m_Wrapper.m_VRControllerHTCActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Joystick_Left.started += instance.OnJoystick_Left;
                @Joystick_Left.performed += instance.OnJoystick_Left;
                @Joystick_Left.canceled += instance.OnJoystick_Left;
                @TrackpadTouched_Left.started += instance.OnTrackpadTouched_Left;
                @TrackpadTouched_Left.performed += instance.OnTrackpadTouched_Left;
                @TrackpadTouched_Left.canceled += instance.OnTrackpadTouched_Left;
            }
        }
    }
    public VRControllerHTCActions @VRControllerHTC => new VRControllerHTCActions(this);
    public interface IVRControllersActions
    {
        void OnTrigger_Right(InputAction.CallbackContext context);
        void OnTrigger_Left(InputAction.CallbackContext context);
        void OnVelocities_Right(InputAction.CallbackContext context);
        void OnVelocities_Left(InputAction.CallbackContext context);
        void OnAngularVelocities_Right(InputAction.CallbackContext context);
        void OnAngularVelocities_Left(InputAction.CallbackContext context);
        void OnButtonPrimary_Right(InputAction.CallbackContext context);
        void OnJoystick_Left(InputAction.CallbackContext context);
    }
    public interface IVRControllerHTCActions
    {
        void OnJoystick_Left(InputAction.CallbackContext context);
        void OnTrackpadTouched_Left(InputAction.CallbackContext context);
    }
}
